# Generated by Django 4.1 on 2022-09-21 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='sample title', max_length=50)),
                ('info', models.CharField(default='sample description', max_length=500)),
                ('url', models.CharField(default='/sample_url', max_length=40)),
                ('lnk', models.CharField(default='hi', max_length=1000)),
                ('cOpen', models.DateTimeField(null=True)),
                ('cCLose', models.DateTimeField(null=True)),
                ('slug', models.SlugField(blank=True, max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_img')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp1', models.FloatField(default=0.0, max_length=3)),
                ('temp2', models.FloatField(default=0.0, max_length=3)),
                ('coverage', models.FloatField(default=0.0, max_length=3)),
                ('contest', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='base.contest')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.profile')),
            ],
        ),
    ]
