# Generated by Django 4.1 on 2022-09-22 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='slug',
            field=models.SlugField(blank=True, max_length=4000, null=True),
        ),
    ]
