# Generated by Django 4.1 on 2022-09-25 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_prediction_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profileSlug',
            field=models.SlugField(blank=True, max_length=20, null=True),
        ),
    ]
